language: node_js
node_js:
  - "5.7.0"
before_script:
  - "npm install"
  - "typings install"
sudo: false
notifications:
  email:
    - yelm-eng@microsoft.com
cache:
  directories:
    - node_modules
    - typings

